<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="My Sample Suite" duration-ms="43" started-at="2014-07-27T15:52:12Z" finished-at="2014-07-27T15:52:12Z">
    <groups>
    </groups>
    <test name="Sample Test Case" duration-ms="20" started-at="2014-07-27T15:52:12Z" finished-at="2014-07-27T15:52:12Z">
      <class name="testcases.SampleTest">
        <test-method status="SKIP" signature="testCaseRegister()[pri:0, instance:testcases.SampleTest@1187984]" name="testCaseRegister" duration-ms="8" started-at="2014-07-27T18:52:12Z" finished-at="2014-07-27T18:52:12Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping test - any reason]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping test - any reason
	at testcases.SampleTest.testCaseRegister(SampleTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseRegister -->
        <test-method status="SKIP" signature="testCaseLoginTest()[pri:0, instance:testcases.SampleTest@1187984]" name="testCaseLoginTest" duration-ms="1" started-at="2014-07-27T18:52:12Z" depends-on-methods="testcases.SampleTest.testCaseRegister" finished-at="2014-07-27T18:52:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseLoginTest -->
        <test-method status="SKIP" signature="testCasePasswordChange()[pri:0, instance:testcases.SampleTest@1187984]" name="testCasePasswordChange" duration-ms="0" started-at="2014-07-27T18:52:12Z" depends-on-methods="testcases.SampleTest.testCaseLoginTest, testcases.SampleTest.testCaseRegister" finished-at="2014-07-27T18:52:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCasePasswordChange -->
      </class> <!-- testcases.SampleTest -->
    </test> <!-- Sample Test Case -->
    <test name="Uploading Pic" duration-ms="2" started-at="2014-07-27T15:52:12Z" finished-at="2014-07-27T15:52:12Z">
      <class name="testcases.UploadPicTest">
        <test-method status="FAIL" signature="uploadPic()[pri:0, instance:testcases.UploadPicTest@1727596]" name="uploadPic" duration-ms="1" started-at="2014-07-27T18:52:12Z" finished-at="2014-07-27T18:52:12Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	The method assertTrue(String, boolean) in the type AssertJUnit is not applicable for the arguments (boolean, String)
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	The method assertTrue(String, boolean) in the type AssertJUnit is not applicable for the arguments (boolean, String)

	at testcases.UploadPicTest.uploadPic(UploadPicTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uploadPic -->
      </class> <!-- testcases.UploadPicTest -->
    </test> <!-- Uploading Pic -->
  </suite> <!-- My Sample Suite -->
</testng-results>
